export enum PokeFilter {
  NAME = "name",
  TYPE = "type",
  BOTH = "nametype",
}

export interface Pokemon {
  id: number;
  name: string;
  type: string[];
  nametype: string;
  hp: number;
  attack: number;
  defense: number;
  special_attack: number;
  special_defense: number;
  speed: number;
}

export default [
  {
    id: 1,
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    hp: 45,
    attack: 49,
    defense: 49,
    special_attack: 65,
    special_defense: 65,
    speed: 45,
  },
  {
    id: 2,
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    hp: 60,
    attack: 62,
    defense: 63,
    special_attack: 80,
    special_defense: 80,
    speed: 60,
  },

  {
    id: 4,
    name: "Charmander",
    type: ["Fire"],
    hp: 39,
    attack: 52,
    defense: 43,
    special_attack: 60,
    special_defense: 50,
    speed: 65,
  },
  {
    id: 5,
    name: "Charmeleon",
    type: ["Fire"],
    hp: 58,
    attack: 64,
    defense: 58,
    special_attack: 80,
    special_defense: 65,
    speed: 80,
  },
  {
    id: 6,
    name: "Charizard",
    type: ["Fire", "Flying"],
    hp: 78,
    attack: 84,
    defense: 78,
    special_attack: 109,
    special_defense: 85,
    speed: 100,
  },
  {
    id: 7,
    name: "Squirtle",
    type: ["Water"],
    hp: 44,
    attack: 48,
    defense: 65,
    special_attack: 50,
    special_defense: 64,
    speed: 43,
  },
  {
    id: 9,
    name: "Blastoise",
    type: ["Water"],
    hp: 79,
    attack: 83,
    defense: 100,
    special_attack: 85,
    special_defense: 105,
    speed: 78,
  },
  {
    id: 12,
    name: "Butterfree",
    type: ["Bug", "Flying"],
    hp: 60,
    attack: 45,
    defense: 50,
    special_attack: 90,
    special_defense: 80,
    speed: 70,
  },
  {
    id: 14,
    name: "Kakuna",
    type: ["Bug", "Poison"],
    hp: 45,
    attack: 25,
    defense: 50,
    special_attack: 25,
    special_defense: 25,
    speed: 35,
  },
  {
    id: 15,
    name: "Beedrill",
    type: ["Bug", "Poison"],
    hp: 65,
    attack: 90,
    defense: 40,
    special_attack: 45,
    special_defense: 80,
    speed: 75,
  },

  {
    id: 19,
    name: "Rattata",
    type: ["Normal"],
    hp: 30,
    attack: 56,
    defense: 35,
    special_attack: 25,
    special_defense: 35,
    speed: 72,
  },
  {
    id: 22,
    name: "Fearow",
    type: ["Normal", "Flying"],
    hp: 65,
    attack: 90,
    defense: 65,
    special_attack: 61,
    special_defense: 61,
    speed: 100,
  },
  {
    id: 23,
    name: "Ekans",
    type: ["Poison"],
    hp: 35,
    attack: 60,
    defense: 44,
    special_attack: 40,
    special_defense: 54,
    speed: 55,
  },
  {
    id: 24,
    name: "Arbok",
    type: ["Poison"],
    hp: 60,
    attack: 95,
    defense: 69,
    special_attack: 65,
    special_defense: 79,
    speed: 80,
  },
  {
    id: 25,
    name: "Pikachu",
    type: ["Electric"],
    hp: 35,
    attack: 55,
    defense: 40,
    special_attack: 50,
    special_defense: 50,
    speed: 90,
  },
  {
    id: 33,
    name: "Nidorino",
    type: ["Poison"],
    hp: 61,
    attack: 72,
    defense: 57,
    special_attack: 55,
    special_defense: 55,
    speed: 65,
  },
  {
    id: 34,
    name: "Nidoking",
    type: ["Poison", "Ground"],
    hp: 81,
    attack: 102,
    defense: 77,
    special_attack: 85,
    special_defense: 75,
    speed: 85,
  },
  {
    id: 35,
    name: "Clefairy",
    type: ["Fairy"],
    hp: 70,
    attack: 45,
    defense: 48,
    special_attack: 60,
    special_defense: 65,
    speed: 35,
  },
  {
    id: 36,
    name: "Clefable",
    type: ["Fairy"],
    hp: 95,
    attack: 70,
    defense: 73,
    special_attack: 95,
    special_defense: 90,
    speed: 60,
  },

  {
    id: 39,
    name: "Jigglypuff",
    type: ["Normal", "Fairy"],
    hp: 115,
    attack: 45,
    defense: 20,
    special_attack: 45,
    special_defense: 25,
    speed: 20,
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: ["Normal", "Fairy"],
    hp: 140,
    attack: 70,
    defense: 45,
    special_attack: 85,
    special_defense: 50,
    speed: 45,
  },
  {
    id: 42,
    name: "Golbat",
    type: ["Poison", "Flying"],
    hp: 75,
    attack: 80,
    defense: 70,
    special_attack: 65,
    special_defense: 75,
    speed: 90,
  },
  {
    id: 44,
    name: "Gloom",
    type: ["Grass", "Poison"],
    hp: 60,
    attack: 65,
    defense: 70,
    special_attack: 85,
    special_defense: 75,
    speed: 40,
  },
  {
    id: 47,
    name: "Parasect",
    type: ["Bug", "Grass"],
    hp: 60,
    attack: 95,
    defense: 80,
    special_attack: 60,
    special_defense: 80,
    speed: 30,
  },
  {
    id: 50,
    name: "Diglett",
    type: ["Ground"],
    hp: 10,
    attack: 55,
    defense: 25,
    special_attack: 35,
    special_defense: 45,
    speed: 95,
  },
  {
    id: 51,
    name: "Dugtrio",
    type: ["Ground"],
    hp: 35,
    attack: 100,
    defense: 50,
    special_attack: 50,
    special_defense: 70,
    speed: 120,
  },
  {
    id: 53,
    name: "Persian",
    type: ["Normal"],
    hp: 65,
    attack: 70,
    defense: 60,
    special_attack: 65,
    special_defense: 65,
    speed: 115,
  },
  {
    id: 54,
    name: "Psyduck",
    type: ["Water"],
    hp: 50,
    attack: 52,
    defense: 48,
    special_attack: 65,
    special_defense: 50,
    speed: 55,
  },
  {
    id: 56,
    name: "Mankey",
    type: ["Fighting"],
    hp: 40,
    attack: 80,
    defense: 35,
    special_attack: 35,
    special_defense: 45,
    speed: 70,
  },
  {
    id: 58,
    name: "Growlithe",
    type: ["Fire"],
    hp: 55,
    attack: 70,
    defense: 45,
    special_attack: 70,
    special_defense: 50,
    speed: 60,
  },
  {
    id: 59,
    name: "Arcanine",
    type: ["Fire"],
    hp: 90,
    attack: 110,
    defense: 80,
    special_attack: 100,
    special_defense: 80,
    speed: 95,
  },
  {
    id: 63,
    name: "Abra",
    type: ["Psychic"],
    hp: 25,
    attack: 20,
    defense: 15,
    special_attack: 105,
    special_defense: 55,
    speed: 90,
  },
  {
    id: 64,
    name: "Kadabra",
    type: ["Psychic"],
    hp: 40,
    attack: 35,
    defense: 30,
    special_attack: 120,
    special_defense: 70,
    speed: 105,
  },
  {
    id: 65,
    name: "Alakazam",
    type: ["Psychic"],
    hp: 55,
    attack: 50,
    defense: 45,
    special_attack: 135,
    special_defense: 95,
    speed: 120,
  },
  {
    id: 66,
    name: "Machop",
    type: ["Fighting"],
    hp: 70,
    attack: 80,
    defense: 50,
    special_attack: 35,
    special_defense: 35,
    speed: 35,
  },
  {
    id: 74,
    name: "Geodude",
    type: ["Rock", "Ground"],
    hp: 40,
    attack: 80,
    defense: 100,
    special_attack: 30,
    special_defense: 30,
    speed: 20,
  },
  {
    id: 75,
    name: "Graveler",
    type: ["Rock", "Ground"],
    hp: 55,
    attack: 95,
    defense: 115,
    special_attack: 45,
    special_defense: 45,
    speed: 35,
  },
  {
    id: 76,
    name: "Golem",
    type: ["Rock", "Ground"],
    hp: 80,
    attack: 120,
    defense: 130,
    special_attack: 55,
    special_defense: 65,
    speed: 45,
  },
  {
    id: 77,
    name: "Ponyta",
    type: ["Fire"],
    hp: 50,
    attack: 85,
    defense: 55,
    special_attack: 65,
    special_defense: 65,
    speed: 90,
  },

  {
    id: 79,
    name: "Slowpoke",
    type: ["Water", "Psychic"],
    hp: 90,
    attack: 65,
    defense: 65,
    special_attack: 40,
    special_defense: 40,
    speed: 15,
  },
  {
    id: 82,
    name: "Magneton",
    type: ["Electric", "Steel"],
    hp: 50,
    attack: 60,
    defense: 95,
    special_attack: 120,
    special_defense: 70,
    speed: 70,
  },
  {
    id: 84,
    name: "Doduo",
    type: ["Normal", "Flying"],
    hp: 35,
    attack: 85,
    defense: 45,
    special_attack: 35,
    special_defense: 35,
    speed: 75,
  },
  {
    id: 85,
    name: "Dodrio",
    type: ["Normal", "Flying"],
    hp: 60,
    attack: 110,
    defense: 70,
    special_attack: 60,
    special_defense: 60,
    speed: 110,
  },
  {
    id: 87,
    name: "Dewgong",
    type: ["Water", "Ice"],
    hp: 90,
    attack: 70,
    defense: 80,
    special_attack: 70,
    special_defense: 95,
    speed: 70,
  },
  {
    id: 91,
    name: "Cloyster",
    type: ["Water", "Ice"],
    hp: 50,
    attack: 95,
    defense: 180,
    special_attack: 85,
    special_defense: 45,
    speed: 70,
  },
  {
    id: 92,
    name: "Gastly",
    type: ["Ghost", "Poison"],
    hp: 30,
    attack: 35,
    defense: 30,
    special_attack: 100,
    special_defense: 35,
    speed: 80,
  },
  {
    id: 93,
    name: "Haunter",
    type: ["Ghost", "Poison"],
    hp: 45,
    attack: 50,
    defense: 45,
    special_attack: 115,
    special_defense: 55,
    speed: 95,
  },
  {
    id: 96,
    name: "Drowzee",
    type: ["Psychic"],
    hp: 60,
    attack: 48,
    defense: 45,
    special_attack: 43,
    special_defense: 90,
    speed: 42,
  },
  {
    id: 97,
    name: "Hypno",
    type: ["Psychic"],
    hp: 85,
    attack: 73,
    defense: 70,
    special_attack: 73,
    special_defense: 115,
    speed: 67,
  },
  {
    id: 98,
    name: "Krabby",
    type: ["Water"],
    hp: 30,
    attack: 105,
    defense: 90,
    special_attack: 25,
    special_defense: 25,
    speed: 50,
  },
  {
    id: 99,
    name: "Kingler",
    type: ["Water"],
    hp: 55,
    attack: 130,
    defense: 115,
    special_attack: 50,
    special_defense: 50,
    speed: 75,
  },
  {
    id: 100,
    name: "Voltorb",
    type: ["Electric"],
    hp: 40,
    attack: 30,
    defense: 50,
    special_attack: 55,
    special_defense: 55,
    speed: 100,
  },
  {
    id: 101,
    name: "Electrode",
    type: ["Electric"],
    hp: 60,
    attack: 50,
    defense: 70,
    special_attack: 80,
    special_defense: 80,
    speed: 150,
  },
  {
    id: 102,
    name: "Exeggcute",
    type: ["Grass", "Psychic"],
    hp: 60,
    attack: 40,
    defense: 80,
    special_attack: 60,
    special_defense: 45,
    speed: 40,
  },
  {
    id: 103,
    name: "Exeggutor",
    type: ["Grass", "Psychic"],
    hp: 95,
    attack: 95,
    defense: 85,
    special_attack: 125,
    special_defense: 75,
    speed: 55,
  },
  {
    id: 104,
    name: "Cubone",
    type: ["Ground"],
    hp: 50,
    attack: 50,
    defense: 95,
    special_attack: 40,
    special_defense: 50,
    speed: 35,
  },
  {
    id: 106,
    name: "Hitmonlee",
    type: ["Fighting"],
    hp: 50,
    attack: 120,
    defense: 53,
    special_attack: 35,
    special_defense: 110,
    speed: 87,
  },
  {
    id: 107,
    name: "Hitmonchan",
    type: ["Fighting"],
    hp: 50,
    attack: 105,
    defense: 79,
    special_attack: 35,
    special_defense: 110,
    speed: 76,
  },
  {
    id: 109,
    name: "Koffing",
    type: ["Poison"],
    hp: 40,
    attack: 65,
    defense: 95,
    special_attack: 60,
    special_defense: 45,
    speed: 35,
  },
  {
    id: 111,
    name: "Rhyhorn",
    type: ["Ground", "Rock"],
    hp: 80,
    attack: 85,
    defense: 95,
    special_attack: 30,
    special_defense: 30,
    speed: 25,
  },
  {
    id: 113,
    name: "Chansey",
    type: ["Normal"],
    hp: 250,
    attack: 5,
    defense: 5,
    special_attack: 35,
    special_defense: 105,
    speed: 50,
  },
  {
    id: 115,
    name: "Kangaskhan",
    type: ["Normal"],
    hp: 105,
    attack: 95,
    defense: 80,
    special_attack: 40,
    special_defense: 80,
    speed: 90,
  },
  {
    id: 116,
    name: "Horsea",
    type: ["Water"],
    hp: 30,
    attack: 40,
    defense: 70,
    special_attack: 70,
    special_defense: 25,
    speed: 60,
  },
  {
    id: 117,
    name: "Seadra",
    type: ["Water"],
    hp: 55,
    attack: 65,
    defense: 95,
    special_attack: 95,
    special_defense: 45,
    speed: 85,
  },
  {
    id: 118,
    name: "Goldeen",
    type: ["Water"],
    hp: 45,
    attack: 67,
    defense: 60,
    special_attack: 35,
    special_defense: 50,
    speed: 63,
  },
  {
    id: 119,
    name: "Seaking",
    type: ["Water"],
    hp: 80,
    attack: 92,
    defense: 65,
    special_attack: 65,
    special_defense: 80,
    speed: 68,
  },
  {
    id: 121,
    name: "Starmie",
    type: ["Water", "Psychic"],
    hp: 60,
    attack: 75,
    defense: 85,
    special_attack: 100,
    special_defense: 85,
    speed: 115,
  },
  {
    id: 123,
    name: "Scyther",
    type: ["Bug", "Flying"],
    hp: 70,
    attack: 110,
    defense: 80,
    special_attack: 55,
    special_defense: 80,
    speed: 105,
  },
  {
    id: 124,
    name: "Jynx",
    type: ["Ice", "Psychic"],
    hp: 65,
    attack: 50,
    defense: 35,
    special_attack: 115,
    special_defense: 95,
    speed: 95,
  },
  {
    id: 125,
    name: "Electabuzz",
    type: ["Electric"],
    hp: 65,
    attack: 83,
    defense: 57,
    special_attack: 95,
    special_defense: 85,
    speed: 105,
  },
  {
    id: 126,
    name: "Magmar",
    type: ["Fire"],
    hp: 65,
    attack: 95,
    defense: 57,
    special_attack: 100,
    special_defense: 85,
    speed: 93,
  },
  {
    id: 128,
    name: "Tauros",
    type: ["Normal"],
    hp: 75,
    attack: 100,
    defense: 95,
    special_attack: 40,
    special_defense: 70,
    speed: 110,
  },
  {
    id: 130,
    name: "Gyarados",
    type: ["Water", "Flying"],
    hp: 95,
    attack: 125,
    defense: 79,
    special_attack: 60,
    special_defense: 100,
    speed: 81,
  },
  {
    id: 131,
    name: "Lapras",
    type: ["Water", "Ice"],
    hp: 130,
    attack: 85,
    defense: 80,
    special_attack: 85,
    special_defense: 95,
    speed: 60,
  },
  {
    id: 132,
    name: "Ditto",
    type: ["Normal"],
    hp: 48,
    attack: 48,
    defense: 48,
    special_attack: 48,
    special_defense: 48,
    speed: 48,
  },
  {
    id: 133,
    name: "Eevee",
    type: ["Normal"],
    hp: 55,
    attack: 55,
    defense: 50,
    special_attack: 45,
    special_defense: 65,
    speed: 55,
  },
  {
    id: 134,
    name: "Vaporeon",
    type: ["Water"],
    hp: 130,
    attack: 65,
    defense: 60,
    special_attack: 110,
    special_defense: 95,
    speed: 65,
  },
  {
    id: 136,
    name: "Flareon",
    type: ["Fire"],
    hp: 65,
    attack: 130,
    defense: 60,
    special_attack: 95,
    special_defense: 110,
    speed: 65,
  },
  {
    id: 137,
    name: "Porygon",
    type: ["Normal"],
    hp: 65,
    attack: 60,
    defense: 70,
    special_attack: 85,
    special_defense: 75,
    speed: 40,
  },
  {
    id: 139,
    name: "Omastar",
    type: ["Rock", "Water"],
    hp: 70,
    attack: 60,
    defense: 125,
    special_attack: 115,
    special_defense: 70,
    speed: 55,
  },
  {
    id: 140,
    name: "Kabuto",
    type: ["Rock", "Water"],
    hp: 30,
    attack: 80,
    defense: 90,
    special_attack: 55,
    special_defense: 45,
    speed: 55,
  },
  {
    id: 141,
    name: "Kabutops",
    type: ["Rock", "Water"],
    hp: 60,
    attack: 115,
    defense: 105,
    special_attack: 65,
    special_defense: 70,
    speed: 80,
  },
  {
    id: 142,
    name: "Aerodactyl",
    type: ["Rock", "Flying"],
    hp: 80,
    attack: 105,
    defense: 65,
    special_attack: 60,
    special_defense: 75,
    speed: 130,
  },
  {
    id: 144,
    name: "Articuno",
    type: ["Ice", "Flying"],
    hp: 90,
    attack: 85,
    defense: 100,
    special_attack: 95,
    special_defense: 125,
    speed: 85,
  },
  {
    id: 146,
    name: "Moltres",
    type: ["Fire", "Flying"],
    hp: 90,
    attack: 100,
    defense: 90,
    special_attack: 125,
    special_defense: 85,
    speed: 90,
  },
  {
    id: 147,
    name: "Dratini",
    type: ["Dragon"],
    hp: 41,
    attack: 64,
    defense: 45,
    special_attack: 50,
    special_defense: 50,
    speed: 50,
  },
  {
    id: 149,
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    hp: 91,
    attack: 134,
    defense: 95,
    special_attack: 100,
    special_defense: 100,
    speed: 80,
  },
  {
    id: 152,
    name: "Chikorita",
    type: ["Grass"],
    hp: 45,
    attack: 49,
    defense: 65,
    special_attack: 49,
    special_defense: 65,
    speed: 45,
  },
  {
    id: 153,
    name: "Bayleef",
    type: ["Grass"],
    hp: 60,
    attack: 62,
    defense: 80,
    special_attack: 63,
    special_defense: 80,
    speed: 60,
  },
  {
    id: 155,
    name: "Cyndaquil",
    type: ["Fire"],
    hp: 39,
    attack: 52,
    defense: 43,
    special_attack: 60,
    special_defense: 50,
    speed: 65,
  },
  {
    id: 159,
    name: "Croconaw",
    type: ["Water"],
    hp: 65,
    attack: 80,
    defense: 80,
    special_attack: 59,
    special_defense: 63,
    speed: 58,
  },
  {
    id: 160,
    name: "Feraligatr",
    type: ["Water"],
    hp: 85,
    attack: 105,
    defense: 100,
    special_attack: 79,
    special_defense: 83,
    speed: 78,
  },
  {
    id: 161,
    name: "Sentret",
    type: ["Normal"],
    hp: 35,
    attack: 46,
    defense: 34,
    special_attack: 35,
    special_defense: 45,
    speed: 20,
  },
  {
    id: 162,
    name: "Furret",
    type: ["Normal"],
    hp: 85,
    attack: 76,
    defense: 64,
    special_attack: 45,
    special_defense: 55,
    speed: 90,
  },
  {
    id: 163,
    name: "Hoothoot",
    type: ["Normal", "Flying"],
    hp: 60,
    attack: 30,
    defense: 30,
    special_attack: 36,
    special_defense: 56,
    speed: 50,
  },
  {
    id: 164,
    name: "Noctowl",
    type: ["Normal", "Flying"],
    hp: 100,
    attack: 50,
    defense: 50,
    special_attack: 86,
    special_defense: 96,
    speed: 70,
  },
  {
    id: 167,
    name: "Spinarak",
    type: ["Bug", "Poison"],
    hp: 40,
    attack: 60,
    defense: 40,
    special_attack: 40,
    special_defense: 40,
    speed: 30,
  },
  {
    id: 168,
    name: "Ariados",
    type: ["Bug", "Poison"],
    hp: 70,
    attack: 90,
    defense: 70,
    special_attack: 60,
    special_defense: 70,
    speed: 40,
  },
  {
    id: 169,
    name: "Crobat",
    type: ["Poison", "Flying"],
    hp: 85,
    attack: 90,
    defense: 80,
    special_attack: 70,
    special_defense: 80,
    speed: 130,
  },
  {
    id: 170,
    name: "Chinchou",
    type: ["Water", "Electric"],
    hp: 75,
    attack: 38,
    defense: 38,
    special_attack: 56,
    special_defense: 56,
    speed: 67,
  },
  {
    id: 171,
    name: "Lanturn",
    type: ["Water", "Electric"],
    hp: 125,
    attack: 58,
    defense: 58,
    special_attack: 76,
    special_defense: 76,
    speed: 67,
  },
  {
    id: 173,
    name: "Cleffa",
    type: ["Fairy"],
    hp: 50,
    attack: 25,
    defense: 28,
    special_attack: 45,
    special_defense: 55,
    speed: 15,
  },
  {
    id: 174,
    name: "Igglybuff",
    type: ["Normal", "Fairy"],
    hp: 90,
    attack: 30,
    defense: 15,
    special_attack: 40,
    special_defense: 20,
    speed: 15,
  },
  {
    id: 179,
    name: "Mareep",
    type: ["Electric"],
    hp: 55,
    attack: 40,
    defense: 40,
    special_attack: 65,
    special_defense: 45,
    speed: 35,
  },
  {
    id: 180,
    name: "Flaaffy",
    type: ["Electric"],
    hp: 70,
    attack: 55,
    defense: 55,
    special_attack: 80,
    special_defense: 60,
    speed: 45,
  },
  {
    id: 181,
    name: "Ampharos",
    type: ["Electric"],
    hp: 90,
    attack: 75,
    defense: 85,
    special_attack: 115,
    special_defense: 90,
    speed: 55,
  },
  {
    id: 184,
    name: "Azumarill",
    type: ["Water", "Fairy"],
    hp: 100,
    attack: 50,
    defense: 80,
    special_attack: 60,
    special_defense: 80,
    speed: 50,
  },
  {
    id: 186,
    name: "Politoed",
    type: ["Water"],
    hp: 90,
    attack: 75,
    defense: 75,
    special_attack: 90,
    special_defense: 100,
    speed: 70,
  },
  {
    id: 187,
    name: "Hoppip",
    type: ["Grass", "Flying"],
    hp: 35,
    attack: 35,
    defense: 40,
    special_attack: 35,
    special_defense: 55,
    speed: 50,
  },
  {
    id: 189,
    name: "Jumpluff",
    type: ["Grass", "Flying"],
    hp: 75,
    attack: 55,
    defense: 70,
    special_attack: 55,
    special_defense: 95,
    speed: 110,
  },
  {
    id: 190,
    name: "Aipom",
    type: ["Normal"],
    hp: 55,
    attack: 70,
    defense: 55,
    special_attack: 40,
    special_defense: 55,
    speed: 85,
  },
  {
    id: 191,
    name: "Sunkern",
    type: ["Grass"],
    hp: 30,
    attack: 30,
    defense: 30,
    special_attack: 30,
    special_defense: 30,
    speed: 30,
  },
  {
    id: 194,
    name: "Wooper",
    type: ["Water", "Ground"],
    hp: 55,
    attack: 45,
    defense: 45,
    special_attack: 25,
    special_defense: 25,
    speed: 15,
  },
  {
    id: 196,
    name: "Espeon",
    type: ["Psychic"],
    hp: 65,
    attack: 65,
    defense: 60,
    special_attack: 130,
    special_defense: 95,
    speed: 110,
  },
  {
    id: 201,
    name: "Unown",
    type: ["Psychic"],
    hp: 48,
    attack: 72,
    defense: 48,
    special_attack: 72,
    special_defense: 48,
    speed: 48,
  },
  {
    id: 203,
    name: "Girafarig",
    type: ["Normal", "Psychic"],
    hp: 70,
    attack: 80,
    defense: 65,
    special_attack: 90,
    special_defense: 65,
    speed: 85,
  },
  {
    id: 206,
    name: "Dunsparce",
    type: ["Normal"],
    hp: 100,
    attack: 70,
    defense: 70,
    special_attack: 65,
    special_defense: 65,
    speed: 45,
  },
  {
    id: 207,
    name: "Gligar",
    type: ["Ground", "Flying"],
    hp: 65,
    attack: 75,
    defense: 105,
    special_attack: 35,
    special_defense: 65,
    speed: 85,
  },
  {
    id: 210,
    name: "Granbull",
    type: ["Fairy"],
    hp: 90,
    attack: 120,
    defense: 75,
    special_attack: 60,
    special_defense: 60,
    speed: 45,
  },
  {
    id: 213,
    name: "Shuckle",
    type: ["Bug", "Rock"],
    hp: 20,
    attack: 10,
    defense: 230,
    special_attack: 10,
    special_defense: 230,
    speed: 5,
  },
  {
    id: 214,
    name: "Heracross",
    type: ["Bug", "Fighting"],
    hp: 80,
    attack: 125,
    defense: 75,
    special_attack: 40,
    special_defense: 95,
    speed: 85,
  },
  {
    id: 217,
    name: "Ursaring",
    type: ["Normal"],
    hp: 90,
    attack: 130,
    defense: 75,
    special_attack: 75,
    special_defense: 75,
    speed: 55,
  },
  {
    id: 220,
    name: "Swinub",
    type: ["Ice", "Ground"],
    hp: 50,
    attack: 50,
    defense: 40,
    special_attack: 30,
    special_defense: 30,
    speed: 50,
  },
  {
    id: 221,
    name: "Piloswine",
    type: ["Ice", "Ground"],
    hp: 100,
    attack: 100,
    defense: 80,
    special_attack: 60,
    special_defense: 60,
    speed: 50,
  },
  {
    id: 222,
    name: "Corsola",
    type: ["Water", "Rock"],
    hp: 65,
    attack: 55,
    defense: 95,
    special_attack: 65,
    special_defense: 95,
    speed: 35,
  },
  {
    id: 225,
    name: "Delibird",
    type: ["Ice", "Flying"],
    hp: 45,
    attack: 55,
    defense: 45,
    special_attack: 65,
    special_defense: 45,
    speed: 75,
  },
  {
    id: 228,
    name: "Houndour",
    type: ["Dark", "Fire"],
    hp: 45,
    attack: 60,
    defense: 30,
    special_attack: 80,
    special_defense: 50,
    speed: 65,
  },
  {
    id: 229,
    name: "Houndoom",
    type: ["Dark", "Fire"],
    hp: 75,
    attack: 90,
    defense: 50,
    special_attack: 110,
    special_defense: 80,
    speed: 95,
  },
  {
    id: 232,
    name: "Donphan",
    type: ["Ground"],
    hp: 90,
    attack: 120,
    defense: 120,
    special_attack: 60,
    special_defense: 60,
    speed: 50,
  },
  {
    id: 233,
    name: "Porygon2",
    type: ["Normal"],
    hp: 85,
    attack: 80,
    defense: 90,
    special_attack: 105,
    special_defense: 95,
    speed: 60,
  },
  {
    id: 234,
    name: "Stantler",
    type: ["Normal"],
    hp: 73,
    attack: 95,
    defense: 62,
    special_attack: 85,
    special_defense: 65,
    speed: 85,
  },
  {
    id: 235,
    name: "Smeargle",
    type: ["Normal"],
    hp: 55,
    attack: 20,
    defense: 35,
    special_attack: 20,
    special_defense: 45,
    speed: 75,
  },
  {
    id: 237,
    name: "Hitmontop",
    type: ["Fighting"],
    hp: 50,
    attack: 95,
    defense: 95,
    special_attack: 35,
    special_defense: 110,
    speed: 70,
  },
  {
    id: 239,
    name: "Elekid",
    type: ["Electric"],
    hp: 45,
    attack: 63,
    defense: 37,
    special_attack: 65,
    special_defense: 55,
    speed: 95,
  },
  {
    id: 242,
    name: "Blissey",
    type: ["Normal"],
    hp: 255,
    attack: 10,
    defense: 10,
    special_attack: 75,
    special_defense: 135,
    speed: 55,
  },
  {
    id: 244,
    name: "Entei",
    type: ["Fire"],
    hp: 115,
    attack: 115,
    defense: 85,
    special_attack: 90,
    special_defense: 75,
    speed: 100,
  },
  {
    id: 245,
    name: "Suicune",
    type: ["Water"],
    hp: 100,
    attack: 75,
    defense: 115,
    special_attack: 90,
    special_defense: 115,
    speed: 85,
  },
  {
    id: 246,
    name: "Larvitar",
    type: ["Rock", "Ground"],
    hp: 50,
    attack: 64,
    defense: 50,
    special_attack: 45,
    special_defense: 50,
    speed: 41,
  },
  {
    id: 248,
    name: "Tyranitar",
    type: ["Rock", "Dark"],
    hp: 100,
    attack: 134,
    defense: 110,
    special_attack: 95,
    special_defense: 100,
    speed: 61,
  },
  {
    id: 250,
    name: "Ho-Oh",
    type: ["Fire", "Flying"],
    hp: 106,
    attack: 130,
    defense: 90,
    special_attack: 110,
    special_defense: 154,
    speed: 90,
  },
  {
    id: 251,
    name: "Celebi",
    type: ["Psychic", "Grass"],
    hp: 100,
    attack: 100,
    defense: 100,
    special_attack: 100,
    special_defense: 100,
    speed: 100,
  },
  {
    id: 253,
    name: "Grovyle",
    type: ["Grass"],
    hp: 50,
    attack: 65,
    defense: 45,
    special_attack: 85,
    special_defense: 65,
    speed: 95,
  },
  {
    id: 254,
    name: "Sceptile",
    type: ["Grass"],
    hp: 70,
    attack: 85,
    defense: 65,
    special_attack: 105,
    special_defense: 85,
    speed: 120,
  },
  {
    id: 256,
    name: "Combusken",
    type: ["Fire", "Fighting"],
    hp: 60,
    attack: 85,
    defense: 60,
    special_attack: 85,
    special_defense: 60,
    speed: 55,
  },
  {
    id: 257,
    name: "Blaziken",
    type: ["Fire", "Fighting"],
    hp: 80,
    attack: 120,
    defense: 70,
    special_attack: 110,
    special_defense: 70,
    speed: 80,
  },
  {
    id: 259,
    name: "Marshtomp",
    type: ["Water", "Ground"],
    hp: 70,
    attack: 85,
    defense: 70,
    special_attack: 60,
    special_defense: 70,
    speed: 50,
  },
  {
    id: 263,
    name: "Zigzagoon",
    type: ["Normal"],
    hp: 38,
    attack: 30,
    defense: 41,
    special_attack: 30,
    special_defense: 41,
    speed: 60,
  },
  {
    id: 267,
    name: "Beautifly",
    type: ["Bug", "Flying"],
    hp: 60,
    attack: 70,
    defense: 50,
    special_attack: 100,
    special_defense: 50,
    speed: 65,
  },
  {
    id: 268,
    name: "Cascoon",
    type: ["Bug"],
    hp: 50,
    attack: 35,
    defense: 55,
    special_attack: 25,
    special_defense: 25,
    speed: 15,
  },
  {
    id: 269,
    name: "Dustox",
    type: ["Bug", "Poison"],
    hp: 60,
    attack: 50,
    defense: 70,
    special_attack: 50,
    special_defense: 90,
    speed: 65,
  },
  {
    id: 272,
    name: "Ludicolo",
    type: ["Water", "Grass"],
    hp: 80,
    attack: 70,
    defense: 70,
    special_attack: 90,
    special_defense: 100,
    speed: 70,
  },
  {
    id: 274,
    name: "Nuzleaf",
    type: ["Grass", "Dark"],
    hp: 70,
    attack: 70,
    defense: 40,
    special_attack: 60,
    special_defense: 40,
    speed: 60,
  },
  {
    id: 281,
    name: "Kirlia",
    type: ["Psychic", "Fairy"],
    hp: 38,
    attack: 35,
    defense: 35,
    special_attack: 65,
    special_defense: 55,
    speed: 50,
  },
  {
    id: 282,
    name: "Gardevoir",
    type: ["Psychic", "Fairy"],
    hp: 68,
    attack: 65,
    defense: 65,
    special_attack: 125,
    special_defense: 115,
    speed: 80,
  },
  {
    id: 283,
    name: "Surskit",
    type: ["Bug", "Water"],
    hp: 40,
    attack: 30,
    defense: 32,
    special_attack: 50,
    special_defense: 52,
    speed: 65,
  },
  {
    id: 286,
    name: "Breloom",
    type: ["Grass", "Fighting"],
    hp: 60,
    attack: 130,
    defense: 80,
    special_attack: 60,
    special_defense: 60,
    speed: 70,
  },
  {
    id: 288,
    name: "Vigoroth",
    type: ["Normal"],
    hp: 80,
    attack: 80,
    defense: 80,
    special_attack: 55,
    special_defense: 55,
    speed: 90,
  },
  {
    id: 294,
    name: "Loudred",
    type: ["Normal"],
    hp: 84,
    attack: 71,
    defense: 43,
    special_attack: 71,
    special_defense: 43,
    speed: 48,
  },
  {
    id: 295,
    name: "Exploud",
    type: ["Normal"],
    hp: 104,
    attack: 91,
    defense: 63,
    special_attack: 91,
    special_defense: 73,
    speed: 68,
  },
  {
    id: 298,
    name: "Azurill",
    type: ["Normal", "Fairy"],
    hp: 50,
    attack: 20,
    defense: 40,
    special_attack: 20,
    special_defense: 40,
    speed: 20,
  },
  {
    id: 299,
    name: "Nosepass",
    type: ["Rock"],
    hp: 30,
    attack: 45,
    defense: 135,
    special_attack: 45,
    special_defense: 90,
    speed: 30,
  },
  {
    id: 300,
    name: "Skitty",
    type: ["Normal"],
    hp: 50,
    attack: 45,
    defense: 45,
    special_attack: 35,
    special_defense: 35,
    speed: 50,
  },
  {
    id: 301,
    name: "Delcatty",
    type: ["Normal"],
    hp: 70,
    attack: 65,
    defense: 65,
    special_attack: 55,
    special_defense: 55,
    speed: 90,
  },
  {
    id: 304,
    name: "Aron",
    type: ["Steel", "Rock"],
    hp: 50,
    attack: 70,
    defense: 100,
    special_attack: 40,
    special_defense: 40,
    speed: 30,
  },
  {
    id: 305,
    name: "Lairon",
    type: ["Steel", "Rock"],
    hp: 60,
    attack: 90,
    defense: 140,
    special_attack: 50,
    special_defense: 50,
    speed: 40,
  },
  {
    id: 306,
    name: "Aggron",
    type: ["Steel", "Rock"],
    hp: 70,
    attack: 110,
    defense: 180,
    special_attack: 60,
    special_defense: 60,
    speed: 50,
  },
  {
    id: 307,
    name: "Meditite",
    type: ["Fighting", "Psychic"],
    hp: 30,
    attack: 40,
    defense: 55,
    special_attack: 40,
    special_defense: 55,
    speed: 60,
  },
  {
    id: 308,
    name: "Medicham",
    type: ["Fighting", "Psychic"],
    hp: 60,
    attack: 60,
    defense: 75,
    special_attack: 60,
    special_defense: 75,
    speed: 80,
  },
  {
    id: 310,
    name: "Manectric",
    type: ["Electric"],
    hp: 70,
    attack: 75,
    defense: 60,
    special_attack: 105,
    special_defense: 60,
    speed: 105,
  },
  {
    id: 313,
    name: "Volbeat",
    type: ["Bug"],
    hp: 65,
    attack: 73,
    defense: 75,
    special_attack: 47,
    special_defense: 85,
    speed: 85,
  },
  {
    id: 314,
    name: "Illumise",
    type: ["Bug"],
    hp: 65,
    attack: 47,
    defense: 75,
    special_attack: 73,
    special_defense: 85,
    speed: 85,
  },
  {
    id: 316,
    name: "Gulpin",
    type: ["Poison"],
    hp: 70,
    attack: 43,
    defense: 53,
    special_attack: 43,
    special_defense: 53,
    speed: 40,
  },
  {
    id: 317,
    name: "Swalot",
    type: ["Poison"],
    hp: 100,
    attack: 73,
    defense: 83,
    special_attack: 73,
    special_defense: 83,
    speed: 55,
  },
  {
    id: 319,
    name: "Sharpedo",
    type: ["Water", "Dark"],
    hp: 70,
    attack: 120,
    defense: 40,
    special_attack: 95,
    special_defense: 40,
    speed: 95,
  },
  {
    id: 320,
    name: "Wailmer",
    type: ["Water"],
    hp: 130,
    attack: 70,
    defense: 35,
    special_attack: 70,
    special_defense: 35,
    speed: 60,
  },
  {
    id: 323,
    name: "Camerupt",
    type: ["Fire", "Ground"],
    hp: 70,
    attack: 100,
    defense: 70,
    special_attack: 105,
    special_defense: 75,
    speed: 40,
  },
  {
    id: 326,
    name: "Grumpig",
    type: ["Psychic"],
    hp: 80,
    attack: 45,
    defense: 65,
    special_attack: 90,
    special_defense: 110,
    speed: 80,
  },
  {
    id: 330,
    name: "Flygon",
    type: ["Ground", "Dragon"],
    hp: 80,
    attack: 100,
    defense: 80,
    special_attack: 80,
    special_defense: 80,
    speed: 100,
  },
  {
    id: 331,
    name: "Cacnea",
    type: ["Grass"],
    hp: 50,
    attack: 85,
    defense: 40,
    special_attack: 85,
    special_defense: 40,
    speed: 35,
  },
  {
    id: 332,
    name: "Cacturne",
    type: ["Grass", "Dark"],
    hp: 70,
    attack: 115,
    defense: 60,
    special_attack: 115,
    special_defense: 60,
    speed: 55,
  },
  {
    id: 335,
    name: "Zangoose",
    type: ["Normal"],
    hp: 73,
    attack: 115,
    defense: 60,
    special_attack: 60,
    special_defense: 60,
    speed: 90,
  },
  {
    id: 338,
    name: "Solrock",
    type: ["Rock", "Psychic"],
    hp: 90,
    attack: 95,
    defense: 85,
    special_attack: 55,
    special_defense: 65,
    speed: 70,
  },
  {
    id: 341,
    name: "Corphish",
    type: ["Water"],
    hp: 43,
    attack: 80,
    defense: 65,
    special_attack: 50,
    special_defense: 35,
    speed: 35,
  },
  {
    id: 342,
    name: "Crawdaunt",
    type: ["Water", "Dark"],
    hp: 63,
    attack: 120,
    defense: 85,
    special_attack: 90,
    special_defense: 55,
    speed: 55,
  },
  {
    id: 343,
    name: "Baltoy",
    type: ["Ground", "Psychic"],
    hp: 40,
    attack: 40,
    defense: 55,
    special_attack: 40,
    special_defense: 70,
    speed: 55,
  },
  {
    id: 344,
    name: "Claydol",
    type: ["Ground", "Psychic"],
    hp: 60,
    attack: 70,
    defense: 105,
    special_attack: 70,
    special_defense: 120,
    speed: 75,
  },
  {
    id: 345,
    name: "Lileep",
    type: ["Rock", "Grass"],
    hp: 66,
    attack: 41,
    defense: 77,
    special_attack: 61,
    special_defense: 87,
    speed: 23,
  },
  {
    id: 346,
    name: "Cradily",
    type: ["Rock", "Grass"],
    hp: 86,
    attack: 81,
    defense: 97,
    special_attack: 81,
    special_defense: 107,
    speed: 43,
  },
  {
    id: 347,
    name: "Anorith",
    type: ["Rock", "Bug"],
    hp: 45,
    attack: 95,
    defense: 50,
    special_attack: 40,
    special_defense: 50,
    speed: 75,
  },
  {
    id: 348,
    name: "Armaldo",
    type: ["Rock", "Bug"],
    hp: 75,
    attack: 125,
    defense: 100,
    special_attack: 70,
    special_defense: 80,
    speed: 45,
  },
  {
    id: 349,
    name: "Feebas",
    type: ["Water"],
    hp: 20,
    attack: 15,
    defense: 20,
    special_attack: 10,
    special_defense: 55,
    speed: 80,
  },
];
